Vagrant.require_version ">= 2.4.1"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.box_version = "202407.22.0"
  config.vm.hostname = "trobinS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "trobinS"
    vb.memory = "1024"
    vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
    kubectl apply -f /vagrant/confs/app1.yaml
    kubectl apply -f /vagrant/confs/app2.yaml
    kubectl apply -f /vagrant/confs/app3.yaml
    kubectl apply -f /vagrant/confs/ingress.yaml
  SHELL
end
