Vagrant.require_version ">= 2.4.1"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"
  config.vm.box_version = "202407.22.0"
  config.vm.hostname = "trobinS"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "trobinS"
    vb.memory = "1024"
    vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -
  SHELL
  config.vm.synced_folder "./deployments", "/home/vagrant/deployments"
  config.vm.provision "shell", inline: <<-SHELL
    kubectl apply -f /home/vagrant/deployments/app1.yaml
    kubectl apply -f /home/vagrant/deployments/app2.yaml
    kubectl apply -f /home/vagrant/deployments/app3.yaml
    kubectl apply -f /home/vagrant/deployments/ingress.yaml
  SHELL
end
