Vagrant.require_version ">= 2.4.1"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.box_version = "202407.22.0"

  # Server Config
  config.vm.define "dbelpaumS" do |dbelpaumS|
    dbelpaumS.vm.hostname = "dbelpaumS"
    dbelpaumS.vm.network "private_network", ip: "192.168.56.110"
    dbelpaumS.vm.provider "virtualbox" do |vb|
      # vb.memory = "2048"
      # vb.cpus = 2
      vb.memory = "1024"
      vb.cpus = 2
    end
    # Server Script
    dbelpaumS.vm.provision "shell", inline: <<-SHELL
      echo "Installing K3s..."
      curl -sfL https://get.k3s.io | sh -
      echo "Sleeping for 20 seconds to wait for service restart..."
      sleep 20
      echo "K3s installed. Retrieving node token..."
      NODE_TOKEN=$(cat /var/lib/rancher/k3s/server/node-token)
      echo "Node token retrieved: $NODE_TOKEN"
      echo $NODE_TOKEN > /vagrant/node_token
    SHELL
  end

  # Worker Config
  config.vm.define "dbelpaumSW" do |dbelpaumSW|
    dbelpaumSW.vm.hostname = "dbelpaumSW"
    dbelpaumSW.vm.network "private_network", ip: "192.168.56.111"
    dbelpaumSW.vm.provider "virtualbox" do |vb|
      # vb.memory = "2048"
      # vb.cpus = 2
      vb.memory = "1024"
      vb.cpus = 2
    end
    # Worker Script
    dbelpaumSW.vm.provision "shell", inline: <<-SHELL
      echo "Waiting for the server to be ready..."
      while ! nc -z 192.168.56.110 6443; do
        sleep 5
      done
      echo "Server is ready. Installing K3s Agent..."
      NODE_TOKEN=$(cat /vagrant/node_token)
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$NODE_TOKEN sh -
    SHELL
  end
  # sudo kubectl -o wide get nodes
  # sudo journalctl -u k3s-agent
  # ip addr show eth1

end
