all up start:
	vagrant up

suspend pause:
	vagrant suspend

reload update:	stop
	vagrant reload

stop halt:
	vagrant halt

status:
	vagrant global-status

list:
	vagrant box list

delete destroy:
	vagrant destroy -f

re:
	vagrant up --provision
