Vagrant.require_version ">= 2.4.1"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.box_version = "202407.22.0"
  config.vm.hostname = "p3"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "p3"
    vb.memory = "1024"
    vb.cpus = 2
  end
  config.vm.synced_folder "./scripts", "/home/vagrant/scripts"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y xfce4 xfce4-goodies
    apt-get install -y lightdm
    apt-get install -y firefox-esr
    systemctl set-default graphical.target
    systemctl enable lightdm
    bash /home/vagrant/scripts/setup.sh
  SHELL
end
